assignment/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from main import views as main_views

urlpatterns = [
    # Examples:
    # url(r'^$', 'assignment.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^cleaners/', include('cleaners.urls', namespace='cleaners')),
    url(r'^customers/', include('customers.urls', namespace='customers')),
    url(r'^$', main_views.home)
]

cleaners/urls.py
from django.conf.urls import url

from .views import (
    CleanerList,
    CleanerDetail,
    CleanerCreation,
    CleanerUpdate,
    CleanerDelete
)

urlpatterns = [

    url(r'^$', CleanerList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', CleanerDetail.as_view(), name='detail'),
    url(r'^new$', CleanerCreation.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', CleanerUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', CleanerDelete.as_view(), name='delete'),

]

customers/urls.py
from django.conf.urls import url

from .views import (
    CustomerList,
    CustomerDetail,
    CustomerCreation,
    CustomerUpdate,
    CustomerDelete
)

urlpatterns = [

    url(r'^$', CustomerList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', CustomerDetail.as_view(), name='detail'),
    url(r'^new$', CustomerCreation.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', CustomerUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', CustomerDelete.as_view(), name='delete'),

]

bookings/models.py
from django.db import models

from customers.models import Customer
from cleaners.models import Cleaner

class Booking(models.Model):
    customer = models.ForeignKey(Customer)
    cleaner = models.ForeignKey(Cleaner)
    date = models.DateTimeField()

cleaners/models.py
from django.db import models

class Cleaner(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    quality_score = models.DecimalField(max_digits=5, decimal_places=2)

customers/models.py
from django.db import models

class Customer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=50)

main/models.py
from django.db import models

bookings/views.py
from django.shortcuts import render

# Create your views here.

cleaners/views.py
from django.core.urlresolvers import reverse_lazy

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)

from .models import Cleaner


class CleanerList(ListView):
    model = Cleaner


class CleanerDetail(DetailView):
    model = Cleaner


class CleanerCreation(CreateView):
    model = Cleaner
    success_url = reverse_lazy('cleaners:list')
    fields = ['first_name', 'last_name', 'quality_score']


class CleanerUpdate(UpdateView):
    model = Cleaner
    success_url = reverse_lazy('cleaners:list')
    fields = ['first_name', 'last_name', 'quality_score']


class CleanerDelete(DeleteView):
    model = Cleaner
    success_url = reverse_lazy('cleaners:list')

customers/views.py
from django.core.urlresolvers import reverse_lazy

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)

from .models import Customer


class CustomerList(ListView):
    model = Customer


class CustomerDetail(DetailView):
    model = Customer


class CustomerCreation(CreateView):
    model = Customer
    success_url = reverse_lazy('customers:list')
    fields = ['first_name', 'last_name', 'phone_number']


class CustomerUpdate(UpdateView):
    model = Customer
    success_url = reverse_lazy('customers:list')
    fields = ['first_name', 'last_name', 'phone_number']


class CustomerDelete(DeleteView):
    model = Customer
    success_url = reverse_lazy('customers:list')

main/views.py
from django.shortcuts import render, redirect


def home(request):
    return render(request, "main/home.html")

cleaners/templates/cleaners/cleaner_confirm_delete.html
{% extends "base.html" %}


{% block content %}
    <form method="post">{% csrf_token %}
        ¿Are you sure you want to delete "{{ object }}"?
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

cleaners/templates/cleaners/cleaner_detail.html
{% extends "base.html" %}


{% block content %}
    <h1>{{ cleaner.first_name }}</h1>
    <p>Score: <i>{{ cleaner.quality_score }}</i></p>
    <p>
        <a href="{% url "cleaners:list" %}">Back</a>
    </p>
{% endblock content %}

cleaners/templates/cleaners/cleaner_form.html
{% extends "base.html" %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

cleaners/templates/cleaners/cleaner_list.html
{% extends "base.html" %}


{% block content %}
    <h1>Cleaners</h1>

    <p>
        <a href="{% url "cleaners:new" %}">Add a cleaner</a>
    </p>
    <table class="table">
        <thead>
          <tr>
                <th>Name</th>
                <th></th>
          </tr>
        </thead>
        <tbody>
            {% for cleaner in object_list %}
                <tr>
                    <td>{{ cleaner.first_name }}</td>
                    <td>
                        <a href="{% url "cleaners:detail" cleaner.id %}">Show</a> |
                        <a href="{% url "cleaners:edit" cleaner.id %}">Edit</a> |
                        <a href="{% url "cleaners:delete" cleaner.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

customers/templates/customers/customer_confirm_delete.html
{% extends "base.html" %}


{% block content %}
    <form method="post">{% csrf_token %}
        ¿Are you sure you want to delete "{{ object }}"?
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

customers/templates/customers/customer_detail.html
{% extends "base.html" %}


{% block content %}
    <h1>{{ customer.first_name }}</h1>
    <p>Score: <i>{{ customer.quality_score }}</i></p>
    <p>
        <a href="{% url "customers:list" %}">Back</a>
    </p>
{% endblock content %}

customers/templates/customers/customer_form.html
{% extends "base.html" %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

customers/templates/customers/customer_list.html
{% extends "base.html" %}


{% block content %}
    <h1>Customers</h1>

    <p>
        <a href="{% url "customers:new" %}">Add a customer</a>
    </p>
    <table class="table">
        <thead>
          <tr>
                <th>Name</th>
                <th></th>
          </tr>
        </thead>
        <tbody>
            {% for customer in object_list %}
                <tr>
                    <td>{{ customer.first_name }}</td>
                    <td>
                        <a href="{% url "customers:detail" customer.id %}">Show</a> |
                        <a href="{% url "customers:edit" customer.id %}">Edit</a> |
                        <a href="{% url "customers:delete" customer.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

main/templates/main/home.html
{% extends "base.html" %}


{% block content %}
    <div class="jumbotron">
        <p>Booking app</p>
    </div>
{% endblock content %}

templates/base.html
{% load staticfiles %}{% spaceless %}
<!doctype html>
    <html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %} :: MyProject</title>
        <meta name="description" content="{% block description %}{% endblock %}">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!--[if lt IE 9]>
            <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
            <script>window.html5 || document.write('<script src="{{ STATIC_URL }}libs/html5shiv.js"><\/script>')</script>
        <![endif]-->
    </head>
    <body>
        <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <a href="/cleaners">Cleaners</a> |
        <a href="/customers">Customers</a>
        <hr>
        {% block content %}{% endblock %}
    </body>
</html>
{% endspaceless %}